import Navbar from "@/components/Navbar";
import Link from "next/link";

export default function ShowcasePage() {
  const projects = [
    {
      title: "Pulse Fintech",
      category: "Dashboard",
      description: "A comprehensive financial analytics platform with real-time charting, wallet management, and multi-currency support.",
      time: "Generated in 45 seconds",
      icon: "📈",
      gradient: "from-blue-500/20 to-amber-500/10"
    },
    {
      title: "BloomCommerce",
      category: "E-Commerce",
      description: "A high-end fashion storefront featuring a beautiful product grid, interactive cart, and clean checkout flow.",
      time: "Generated in 52 seconds",
      icon: "🛍️",
      gradient: "from-pink-500/20 to-amber-500/10"
    },
    {
      title: "Aura Social",
      category: "Social Media",
      description: "A minimalist social feed with profile customization, photo uploads, and an incredibly smooth glassmorphism UI.",
      time: "Generated in 38 seconds",
      icon: "📱",
      gradient: "from-purple-500/20 to-amber-500/10"
    },
    {
      title: "HiveFlow Task",
      category: "Productivity",
      description: "Kanban style task management app with drag-and-drop support, team collaboration, and notification systems.",
      time: "Generated in 61 seconds",
      icon: "⚡",
      gradient: "from-green-500/20 to-amber-500/10"
    }
  ];

  return (
    <main className="min-h-screen relative overflow-hidden bg-black selection:bg-amber-500/30">
      <Navbar />

      <div className="absolute top-1/4 left-1/4 w-[600px] h-[600px] bg-amber-500/10 rounded-full blur-[140px] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-[500px] h-[500px] bg-yellow-500/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="relative z-10 flex flex-col items-center pt-32 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto text-center">
          <div className="mb-6 inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-400 text-xs font-semibold tracking-wider">
            SHOWCASE GALLERY
          </div>

          <h1 className="text-5xl sm:text-7xl font-extrabold text-transparent bg-clip-text bg-gradient-to-b from-white via-amber-100 to-amber-500 mb-6 tracking-tight">
            The Hive Gallery.
          </h1>

          <p className="text-xl text-amber-100/70 mb-20 max-w-2xl mx-auto font-light leading-relaxed">
            Witness the incredible speed and quality of applications generated by the Lovabee swarm intelligence. These are real apps, built in seconds.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 mb-20">
            {projects.map((project) => (
              <div key={project.title} className="group relative bg-[#0a0a0a] rounded-[2.5rem] border border-gray-800 overflow-hidden hover:border-amber-500/50 transition-all duration-500 shadow-2xl">
                <div className={`h-64 bg-gradient-to-br ${project.gradient} flex items-center justify-center relative overflow-hidden`}>
                  <span className="text-8xl transform group-hover:scale-125 transition-transform duration-700">{project.icon}</span>
                  <div className="absolute top-4 right-4 bg-black/50 backdrop-blur-md px-4 py-1.5 rounded-full text-[10px] font-bold text-amber-400 uppercase tracking-widest border border-amber-500/30">
                    Live Demo
                  </div>
                </div>
                
                <div className="p-10 text-left">
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-amber-500 font-mono text-xs font-bold uppercase tracking-widest">{project.category}</span>
                    <span className="text-gray-500 text-xs">{project.time}</span>
                  </div>
                  <h3 className="text-3xl font-bold text-white mb-4 group-hover:text-amber-400 transition-colors">{project.title}</h3>
                  <p className="text-gray-450 leading-relaxed mb-8">
                    {project.description}
                  </p>
                  <button className="flex items-center gap-2 text-white font-bold hover:text-amber-500 transition-colors">
                    Explore Project <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" /></svg>
                  </button>
                </div>
              </div>
            ))}
          </div>

          <div className="p-16 rounded-[3rem] bg-[#0a0a0a] border-2 border-dashed border-amber-500/20 text-center">
            <h3 className="text-4xl font-bold text-white mb-6">Want your app here?</h3>
            <p className="text-gray-400 mb-10 max-w-xl mx-auto">
              Join thousands of developers using Lovabee to turn their complex ideas into high-quality code.
            </p>
            <Link href="/" className="inline-block px-12 py-5 bg-amber-500 text-black font-extrabold rounded-2xl hover:bg-amber-400 shadow-xl shadow-amber-500/10 transition-all">
              Build your first app
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
